language: python
sudo: false
python:
  - "2.7"
before_install:
  - openssl aes-256-cbc -K $encrypted_42099b4af021_key -iv $encrypted_42099b4af021_iv -in spokehub_rsa.enc -out spokehub_rsa -d
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python manage.py test spokehub
  - coverage run --source=spokehub manage.py test spokehub
after_success:
  - coveralls
  - chmod 600 spokehub_rsa
  - ssh-add spokehub_rsa
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && make travis_deploy
