db:
  image: postgres
web:
  image: thraxil/spokehub
  command: manage runserver 0.0.0.0:8000
  environment:
    - SETTINGS=settings_compose
  volumes:
    - .:/app/
  ports:
    - "8000:8000"
  links:
    - db
